<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aura3D.Avalonia" Version="2.0.0-pre-release.20251210" />
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />

    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="$(AvaloniaDiagnosticsVersion)" />
    <!--<PackageReference Include="nmarkup" Version="$(nmarkupVersion)" />-->
    <PackageReference Include="NStyles.MeterialIcons" Version="$(AvaloniaVersion)" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="Assets\ainimal.glb">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\nbui\NewBeeUI.Platforms\NewBeeUI.Platforms.csproj" />
    <ProjectReference Include="..\..\nbui\NewBeeUI\NewBeeUI.csproj" />
    <ProjectReference Include="..\..\nstyles\source\NStyles\NStyles.csproj" />
  </ItemGroup>
</Project>
