<Project>
	<PropertyGroup>
		<Version>12.0.0.2</Version>
  </PropertyGroup>
  <PropertyGroup>
    <nmarkupVersion>12.0.0.3</nmarkupVersion>
    <AvaloniaVersion>12.0.0</AvaloniaVersion>
    <AvaloniaDiagnosticsVersion>11.3.13</AvaloniaDiagnosticsVersion>
    <SkiaSharpVersion>3.119.3-preview.1.1</SkiaSharpVersion>
  </PropertyGroup>
  <!--<ItemGroup>
    <PackageVersion Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Skia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="SkiaSharp" Version="$(SkiaSharpVersion)" />
    <PackageVersion Include="nmarkup" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="NStyles.MeterialIcons" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>-->
</Project>
