<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RepositoryUrl>https://github.com/nscript-site/nscript-solution</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageId>nstyles</PackageId>
    <PackageTags>avalonia</PackageTags>
    <PackageProjectUrl>https://github.com/nscript-site/nscript-solution</PackageProjectUrl>
    <Copyright>geblab.com</Copyright>
    <Title>A avalonia ui utils library based on sukiui</Title>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IncludeSymbols>False</IncludeSymbols>
    <Company>geblab</Company>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Properties\Shaders\Background\backgroundshadcn.sksl" />
    <None Remove="Properties\Shaders\Background\bubble.sksl" />
    <None Remove="Properties\Shaders\Background\bubblestrong.sksl" />
    <None Remove="Properties\Shaders\Background\cells.sksl" />
    <None Remove="Properties\Shaders\Background\flat.sksl" />
    <None Remove="Properties\Shaders\Background\gradient.sksl" />
    <None Remove="Properties\Shaders\Background\gradientdarker.sksl" />
    <None Remove="Properties\Shaders\Background\gradientsoft.sksl" />
    <None Remove="Properties\Shaders\Background\waves.sksl" />
    <None Remove="Properties\Shaders\Loading\glow.sksl" />
    <None Remove="Properties\Shaders\Loading\pellets.sksl" />
    <None Remove="Properties\Shaders\Loading\simple.sksl" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Properties\Shaders\Background\backgroundshadcn.sksl" />
    <EmbeddedResource Include="Properties\Shaders\Background\bubble.sksl" />
    <EmbeddedResource Include="Properties\Shaders\Background\bubblestrong.sksl" />
    <EmbeddedResource Include="Properties\Shaders\Background\cells.sksl" />
    <EmbeddedResource Include="Properties\Shaders\Background\flat.sksl" />
    <EmbeddedResource Include="Properties\Shaders\Background\gradient.sksl" />
    <EmbeddedResource Include="Properties\Shaders\Background\gradientdarker.sksl" />
    <EmbeddedResource Include="Properties\Shaders\Background\gradientsoft.sksl" />
    <EmbeddedResource Include="Properties\Shaders\Background\waves.sksl" />
    <EmbeddedResource Include="Properties\Shaders\Loading\glow.sksl" />
    <EmbeddedResource Include="Properties\Shaders\Loading\pellets.sksl" />
    <EmbeddedResource Include="Properties\Shaders\Loading\simple.sksl" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="$(SkiaSharpVersion)" />
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Skia" Version="$(AvaloniaVersion)" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Controls\CherylGlassCard.axaml.cs">
      <DependentUpon>CherylGlassCard.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="Theme\ProgressBarStyles.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Theme\RepeatButton.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Theme\TextBlock.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>
</Project>
