using System.Text;
using System.Xml.Linq;

namespace NStyles.SvgIconGenerator;

public class IconSourceGenerator
{
    static string TemplateText = String.Empty;

    public static void GenerateIcons(string path, string ns, string outputFileName = "Icons.cs")
    {
        TemplateText = File.ReadAllText("Template.txt");

        var sb = new StringBuilder();
        var dir = new DirectoryInfo(path);
        var files = dir.GetFiles("*.svg", SearchOption.AllDirectories);

        sb.AppendLine($"// This file is auto-generated by Generator. Do not edit it manually.");
        sb.AppendLine("using Avalonia.Media;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");

        foreach (var file in files)
        {
            var g = Generate(file);
            if (string.IsNullOrEmpty(g) == false)
            {
                sb.AppendLine(g);
            }
        }
        File.WriteAllText(outputFileName, sb.ToString());
    }

    internal static string Generate(FileInfo fileInfo)
    {
        Console.WriteLine($"Generating {fileInfo.Name}...");

        var sb = new StringBuilder();
        var name = fileInfo.Name;
        if (name.EndsWith(".svg") == false) return string.Empty;

        // Remove the ".svg" extension and replace dots with dashes
        name = name.Substring(0, name.Length - 4);

        // Replace dots with dashes to create a valid class name
        name = name.Replace(".", "-");

        var terms = name.Split('-');
        foreach (var term in terms)
        {
            sb.Append(char.ToUpper(term[0]));
            sb.Append(term.Substring(1));
        }
        var className = sb.ToString();

        if (className.Length > 0 && Char.IsDigit(className[0]))
        {
            className = $"Icon_{className}";
        }

        var path = ParsePath(fileInfo.FullName);
        if (string.IsNullOrEmpty(path)) return string.Empty;

        sb.Clear();

        var template = TemplateText.Replace("SearchIcon", $"{className}Icon");
        template = template.Replace("SVGVALUE", path);
        sb.AppendLine(template);
        sb.AppendLine();
        return sb.ToString();
    }

    internal static string ParsePath(string svgFilePath)
    {
        var svgContent = File.ReadAllText(svgFilePath);

        // 解析 SVG 文件
        var svgDocument = XDocument.Parse(svgContent);

        // 提取 <path> 元素的 d 属性值
        var pathElements = svgDocument.Descendants()
                                      .Where(e => e.Name.LocalName == "path");

        foreach (var pathElement in pathElements)
        {
            var dAttribute = pathElement.Attribute("d");
            if (dAttribute != null)
            {
                return dAttribute.Value;
            }
        }

        return string.Empty;
    }
}
